# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: subscription-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - subscription-network

  redis:
    image: redis:latest
    container_name: subscription-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - subscription-network

volumes:
  postgres_data:
  redis_data:

networks:
  subscription-network:
    driver: bridge
